FROM registry.access.redhat.com/jboss-datavirt-6/datavirt63-openshift

LABEL Name="JDV KING DOP Demo" Version="latest"

#COPY modules /extensions/modules/
COPY install.sh /extensions/
COPY install.properties /extensions/
